### ISSUE TITLE
standalone ? 

### ISSUE THREAD

**Issue by nHxJaco** [cowardtv/LaunchControl#1]
how do i make it stand alone mate >

**Comment by cowardtv** [comment]
just change the notification and thats it

**Comment by nHxJaco** [comment]
> just change the notification and thats it

ok can you add my discord LikkleJamo#9079 i got it to work but has to be reset every time to use ?

**Comment by nHxJaco** [comment]
> just change the notification and thats it

thanks for replying so fast also
